# Generated by Django 5.0.1 on 2024-05-06 05:47

import django.db.models.deletion
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_level', models.CharField(blank=True, default='', max_length=50)),
                ('preferred_sports', models.TextField(blank=True, default='')),
                ('participation_history', models.TextField(blank=True, default='')),
                ('coaching_details', models.TextField(blank=True, default='')),
                ('medical_information', models.TextField(blank=True, default='')),
                ('equipment', models.TextField(blank=True, default='')),
                ('privacy_settings', models.JSONField(blank=True, default=users.models.default_privacy_settings)),
                ('receive_newsletters', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('club_memberships', models.ManyToManyField(blank=True, related_name='user_profile', to='clubs.club')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
