# Generated by Django 5.0.1 on 2024-04-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='club_membership',
            new_name='club_memberships',
        ),
    ]
