# Generated by Django 5.0.1 on 2025-04-23 11:14

import django.db.models.deletion
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0002_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coaching_details',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='participation_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_settings',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='club_memberships',
            field=models.ManyToManyField(blank=True, related_name='user_memberships', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_information',
            field=models.TextField(blank=True, verbose_name='Медицинская информация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_sports',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предпочтительные виды спорта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=True, verbose_name='Публичный профиль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_newsletters',
            field=models.BooleanField(default=False, verbose_name='Получать новости'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_newsletters', models.BooleanField(default=False, verbose_name='Получать новости')),
                ('public_profile', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('privacy_settings', models.JSONField(blank=True, default=users.models.default_privacy_settings, verbose_name='Настройки приватности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
