# Generated by Django 5.0.1 on 2024-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
