# Generated by Django 5.0.4 on 2024-04-12 11:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_newsletters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=users.models.default_privacy_settings),
        ),
    ]
