# Generated by Django 5.0.1 on 2025-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='EventTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
