# Generated by Django 5.0.1 on 2025-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_pagevisit_page_url_pagevisit_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='page_url',
            field=models.URLField(default='/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('event_participation', 'Event Participation'), ('content_interaction', 'Content Interaction')], max_length=50),
        ),
    ]
