# Generated by Django 5.0.1 on 2025-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_pagevisit_page_url_alter_pagevisit_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
