# Generated by Django 5.0.1 on 2025-05-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={},
        ),
        migrations.AddField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
